sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project learning-k8s-275620
  - gcloud config set compute/zone europe-west1-b	
  - gcloud container clusters get-credentials learning-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t basov/docker-complex-frontend -f ./frontend/Dockerfile.dev ./frontend
script:
  - docker run -e CI=true basov/docker-complex-frontend npm run test:unit
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master